import type { Order } from "../../../../packages/shared/src/types";
import { Modal } from "./UI";
import { date, money } from "../lib/api";
export function OrderDocument({
  order,
  kind,
  onClose,
}: {
  order: Order;
  kind: "Purchase order" | "Delivery challan";
  onClose: () => void;
}) {
  return (
    <Modal title={kind} onClose={onClose} wide>
      <div className="print-document">
        <div className="document-brand">
          CMEMP <span>Materials & procurement</span>
        </div>
        <h1>{kind}</h1>
        <p>
          {kind === "Purchase order" ? "PO" : "DC"}-{order.id} · Issued{" "}
          {date(order.createdAt)}
        </p>
        <div className="form-grid">
          <div>
            <h3>Deliver to</h3>
            <p>
              {order.customerName}
              <br />
              {order.project}
              <br />
              {order.address} — {order.pincode}
            </p>
          </div>
          <div>
            <h3>Supplier</h3>
            <p>
              {order.quote.supplierName}
              <br />
              Order: {order.id}
              <br />
              Status: {order.status}
            </p>
          </div>
        </div>
        <table>
          <thead>
            <tr>
              <th>Material</th>
              <th>Quantity</th>
              {kind === "Purchase order" && (
                <>
                  <th>Rate</th>
                  <th>Amount</th>
                </>
              )}
            </tr>
          </thead>
          <tbody>
            {order.quote.items.map((i) => (
              <tr key={i.productId}>
                <td>{i.name}</td>
                <td>
                  {i.qty} {i.unit}
                </td>
                {kind === "Purchase order" && (
                  <>
                    <td>{money(i.rate)}</td>
                    <td>{money(Math.round(i.qty * i.rate))}</td>
                  </>
                )}
              </tr>
            ))}
          </tbody>
        </table>
        {kind === "Purchase order" ? (
          <>
            <div className="document-totals">
              <p>
                Subtotal <strong>{money(order.quote.subtotal)}</strong>
              </p>
              <p>
                GST <strong>{money(order.quote.tax)}</strong>
              </p>
              <p>
                Freight (inclusive){" "}
                <strong>{money(order.quote.freight)}</strong>
              </p>
              <p>
                Total <strong>{money(order.quote.total)}</strong>
              </p>
            </div>
            <p>Payment terms: {order.quote.terms}</p>
          </>
        ) : (
          <>
            <p>
              Vehicle: {order.vehicle || "Awaiting assignment"} · Driver:{" "}
              {order.driver || "Awaiting assignment"}
            </p>
            <div className="signatures">
              <span>Dispatched by: __________________</span>
              <span>Received by: __________________</span>
            </div>
          </>
        )}
        <p className="muted">
          Operational record generated by CMEMP. Not a tax invoice. Verify
          quantities and statutory transport documentation before dispatch.
        </p>
      </div>
      <button
        className="button primary no-print"
        onClick={() => window.print()}
      >
        Print / save as PDF
      </button>
    </Modal>
  );
}
